# Generated by Django 5.1.5 on 2025-02-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='special',
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
